"""
10_Water.py
Difference in water yield relative to 2010 by land use and agricultural management.
Positive = more water yield than 2010 baseline (beneficial).
Overview row decomposes the water-yield difference into land-use and climate
components using the CCI (Climate Change Impact) already computed by write.py.
"""
import _path_setup  # noqa: F401

import os

import pandas as pd

from tools.parameters import GENERATE_TABLES, EXCEL_DIR
from tools.two_row_figure import (
    LU_COLORS,
    RENAME_AM_NON_AG,
    classify_land_use,
    export_long_tables,
    filter_water_detail_rows,
    get_am_colors,
    input_files,
    load_long_tables,
    load_report_source_csv,
    save_three_row_figure,
)
from tools.data_helper import list_output_years, load_output_dataset

VALUE_COL = 'Water Net Yield (ML)'
SOURCE_CSV = 'water_yield_separate_watershed'
CCI_CSV = 'water_yield_limits_and_public_land'
CCI_COL = 'Climate Change Impact (ML)'

OVERVIEW_COLORS = {
    'Land use impact': '#6eabb1',
    'Climate change impact': '#d95f02',
}

WATER_LAND_USE_LEGEND_ORDER = [
    'Dryland cropland and horticulture',
    'Dryland grazing (modified pastures)',
    'Grazing (native vegetation)',
    'Irrigated cropland and horticulture',
    'Unallocated land',
    'Non-agricultural land-use',
    'Irrigated grazing (modified pastures)',
]

def load_water_australia(scenario):
    water = load_report_source_csv(scenario, SOURCE_CSV)
    if water.empty:
        return water
    return filter_water_detail_rows(water).replace(RENAME_AM_NON_AG)


_CLIMATE_WATER_CACHE = None


def _load_climate_impact(scenario):
    """Pure climate impact on water yield (GL) per year, dry+irr summed, for a scenario.

    Reads 03_water_climate_impact_split.csv (generated by 03_indicators.py from the raw
    Data_RES*.lz4 objects). This is the water-YIELD change only — the livestock
    water-requirement change that write.py folds into its reported CCI is excluded, so
    only the true, scenario-invariant climate signal is reported here.
    """
    global _CLIMATE_WATER_CACHE
    if _CLIMATE_WATER_CACHE is None:
        path = os.path.join(EXCEL_DIR, '03_water_climate_impact_split.csv')
        if not os.path.exists(path):
            raise FileNotFoundError(
                f'Missing water climate-impact split: {path}\n'
                'Run  python 03_indicators.py  (xpluto env) first — it generates this cache '
                'from the raw Data_RES*.lz4 objects.'
            )
        _CLIMATE_WATER_CACHE = pd.read_csv(path)
    df = _CLIMATE_WATER_CACHE
    df = df[df['scenario'] == scenario]
    return {int(r['year']): float(r['dry_climate_GL'] + r['irr_climate_GL'])
            for _, r in df.iterrows()}


def _subtract_2010_baseline(rows_list):
    """Given a list of row dicts (year, scenario, category, value),
    subtract the 2010 value for each (scenario, category) pair."""
    df = pd.DataFrame(rows_list)
    if df.empty:
        return df
    baseline = (
        df[df['year'] == 2010]
        .set_index(['scenario', 'category'])['value']
    )
    def sub_baseline(row):
        key = (row['scenario'], row['category'])
        return row['value'] - baseline.get(key, 0.0)
    df['value'] = df.apply(sub_baseline, axis=1)
    return df


def _load_water_correction_by_category(scenario):
    """
    Attribute the 2010 agricultural water yield of cells converted to non-ag
    land-use back to the original dryland/irrigated land-use categories.

    This mirrors the correction used in 03_indicators.py, but keeps the
    attribution at the detailed land-use legend level used in this figure.
    """
    ds = load_output_dataset(scenario, 2010, 'xr_water_yield_ag_2010.nc')
    if ds is None:
        return {}

    try:
        data = ds['data'].values
        lu_names = [str(v) for v in ds['lu'].values]
        n_lu = len(lu_names)
        lm_index = {'dry': 1, 'irr': 2}
        category_layers = {}
        for lu_idx, lu_name in enumerate(lu_names):
            if lu_name == 'ALL':
                continue
            for lm_name, lm_idx in lm_index.items():
                category = classify_land_use(lu_name, lm_name)
                if category is None:
                    continue
                layer_idx = lm_idx * n_lu + lu_idx
                category_layers.setdefault(category, []).append(data[:, layer_idx])
    except Exception:
        return {}
    finally:
        ds.close()

    corrections = {}
    for year in list_output_years(scenario):
        if year == 2010:
            corrections[year] = {}
            continue

        ds_nag = load_output_dataset(scenario, year, f'xr_water_yield_non_ag_{year}.nc')
        if ds_nag is None:
            corrections[year] = {}
            continue

        try:
            mask = ds_nag['data'].values[:, 0] > 0
            corrections[year] = {
                category: float(sum(layer[mask].sum() for layer in layers))
                for category, layers in category_layers.items()
            }
        except Exception:
            corrections[year] = {}
        finally:
            ds_nag.close()
    return corrections


def prepare_overview():
    """Overview row: two components — land use impact and climate change impact.
    Climate change impact = PURE climate water-yield change (scenario-invariant; read from
    the 03_water_climate_impact_split.csv cache generated by 03_indicators.py). Land use
    impact = total water yield change minus that pure
    climate signal, so it also carries the small livestock water-requirement change that
    write.py otherwise folds into its reported CCI (a management, not climate, effect).
    """
    rows = []
    for scenario in input_files:
        water = load_water_australia(scenario)
        if water.empty:
            continue

        clim_by_year = _load_climate_impact(scenario)

        # Total water yield per year (absolute, GL) — all types combined
        total_by_year = (
            water.groupby('Year')[VALUE_COL].sum() / 1e3
        ).to_dict()
        total_baseline = total_by_year.get(2010, 0.0)

        all_years = sorted(set(total_by_year) | set(clim_by_year))
        for year in all_years:
            total_delta = total_by_year.get(year, 0.0) - total_baseline
            clim_val    = clim_by_year.get(year, 0.0)
            lu_impact   = total_delta - clim_val   # land use + livestock-water-req change
            rows.append({
                'year': int(year), 'scenario': scenario,
                'category': 'Land use impact', 'value': lu_impact,
            })
            rows.append({
                'year': int(year), 'scenario': scenario,
                'category': 'Climate change impact', 'value': clim_val,
            })

    return pd.DataFrame(rows)


def prepare_land_use():
    rows = []
    for scenario in input_files:
        water = load_water_australia(scenario)
        if water.empty:
            continue

        water_ag = water.query('Type == "Agricultural Land-use"').copy()
        if not water_ag.empty:
            water_ag['category'] = water_ag.apply(
                lambda r: classify_land_use(r['Landuse'], r['Water Supply']), axis=1
            )
            water_ag = water_ag.dropna(subset=['category'])
            water_ag = water_ag.groupby(['Year', 'category'], as_index=False)[VALUE_COL].sum()

        water_non_ag = water.query('Type == "Non-Agricultural Land-use"').copy()
        if not water_non_ag.empty:
            water_non_ag = water_non_ag.groupby('Year', as_index=False)[VALUE_COL].sum()

        ag_values = (
            {} if water_ag.empty else
            water_ag.set_index(['Year', 'category'])[VALUE_COL].to_dict()
        )
        non_ag_values = (
            {} if water_non_ag.empty else
            water_non_ag.set_index('Year')[VALUE_COL].to_dict()
        )
        baseline = {
            category: ag_values.get((2010, category), 0.0)
            for category in LU_COLORS
            if category != 'Non-agricultural land-use'
        }
        baseline_non_ag = non_ag_values.get(2010, 0.0)

        corrections = _load_water_correction_by_category(scenario)

        all_years = sorted(
            {year for year, _ in ag_values}
            | set(non_ag_values)
            | set(corrections)
        )
        for year in all_years:
            correction_by_category = corrections.get(int(year), {})
            total_correction = sum(correction_by_category.values())
            for category in LU_COLORS:
                if category == 'Non-agricultural land-use':
                    value = non_ag_values.get(year, 0.0) - baseline_non_ag - total_correction
                else:
                    value = (
                        ag_values.get((year, category), 0.0)
                        - baseline.get(category, 0.0)
                        + correction_by_category.get(category, 0.0)
                    )
                rows.append({
                    'year': int(year),
                    'scenario': scenario,
                    'category': category,
                    'value': value / 1e3,
                })

    return pd.DataFrame(rows)


def prepare_am():
    rows = []
    for scenario in input_files:
        water = load_water_australia(scenario)
        if water.empty:
            continue
        water = water.query('Type == "Agricultural Management"').copy()
        water = water.groupby(['Year', 'Agricultural Management'], as_index=False)[VALUE_COL].sum()
        for _, row in water.iterrows():
            rows.append({
                'year':     int(row['Year']),
                'scenario': scenario,
                'category': row['Agricultural Management'],
                'value':    float(row[VALUE_COL]) / 1e3,
            })
    return _subtract_2010_baseline(rows)


def main():
    workbook = '19_water_long_tables.xlsx'
    if GENERATE_TABLES:
        export_long_tables(
            workbook,
            overview=prepare_overview(),
            land_use=prepare_land_use(),
            agricultural_management=prepare_am(),
        )
    tables = load_long_tables(workbook, 'overview', 'land_use', 'agricultural_management')
    overview_df = tables['overview']
    land_use_df = tables['land_use']
    am_df       = tables['agricultural_management']
    am_colors = {
        label: color
        for label, color in get_am_colors().items()
        if label != 'Other land-use'
    }
    save_three_row_figure(
        overview_df,
        land_use_df,
        am_df,
        OVERVIEW_COLORS,
        LU_COLORS,
        am_colors,
        'Difference in water yield relative to 2010 (GL yr⁻¹)',
        '19_water.svg',
        y_label_x=-0.006,
        top_legend_order=WATER_LAND_USE_LEGEND_ORDER,
    )


if __name__ == '__main__':
    main()
