name: luto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy==1.26.4
  - pandas==2.2.2
  - rasterio==1.3.9
  - scipy==1.13.0
  - matplotlib==3.8.4
  - h5py==3.11.0
  - openpyxl==3.1.2
  - pytest==8.2.1
  - pytables==3.9.2
  - hypothesis==6.102.4
  - lxml==5.2.2
  - folium==0.16.0
  - contextily==1.6.0
  - imageio==2.34.1
  - geopandas==0.14.4
  - ipython==8.24.0
  - rioxarray==0.15.5
  - xarray==2024.5.0
  - dask==2024.5.1
  - h5netcdf==1.3.0
  - ipykernel==6.29.4
  - sparse==0.15.4
  - nbformat==5.10.4
  - dill==0.3.8
  - pip
  - pip:
      - gurobipy==12.0.0
      - numpy_financial==1.0.0
      - tables==3.9.2