name: luto

channels:
  - conda-forge
  - defaults

dependencies:
  # --- 核心环境 ---
  - python=3.12

  # --- 地理空间底层依赖 (显式添加以避免 DLL 冲突) ---
  - gdal=3.8.*           # 明确安装 GDAL - 这是关键！
  - proj=9.3.*           # 投影库
  - geos=3.12.*          # 几何操作库
  - fiona=1.9.*          # 矢量文件读写 (geopandas 依赖)
  - shapely=2.0.*        # 几何对象 (geopandas 依赖)
  - pyproj=3.6.*         # 投影转换 (geopandas 依赖)
  - rasterio=1.3.*       # 栅格文件读写 (rioxarray 依赖)

  # --- 地理空间处理 (你的原版本) ---
  - geopandas=0.14.4     # 会自动安装 pandas, fiona, shapely, pyproj 等
  - rioxarray=0.15.5     # 会自动安装 rasterio, xarray
  - contextily=1.6.0
  - folium=0.16.0

  # --- 数据科学与分析 (你的原版本) ---
  - scikit-learn=1.6.0   # 会自动安装 numpy, scipy
  - pytables=3.9.2
  - netcdf4=1.7.1
  - h5py=3.11.0
  - dask=2024.5.1
  - numba=0.60.0
  - pyarrow=17.0.0

  # --- 可视化与交互 (你的原版本) ---
  - matplotlib=3.8.4
  - jupyterlab=4.2.6     # 会自动安装 notebook, ipykernel, ipywidgets 等
  - bokeh=3.6.2

  # --- 实用工具 (你的原版本) ---
  - openpyxl=3.1.2
  - lxml=5.2.2
  - requests=2.32.3
  - tqdm=4.67.1

  # --- 系统稳定性依赖 (Windows DLL 支持) ---
  - ca-certificates      # SSL 证书
  - certifi              # Python SSL 证书

  # --- Pip 安装 (你的原版本 + 一些有用的补充) ---
  - pip=24.*
  - pip:
    - gurobipy==11.0.2
    - numpy-financial==1.0.0
    - memory-profiler==0.61.0